#!/usr/bin/env bash
###############################################################################
# connect-workshop.sh — attendee-side workshop connection setup.
#
# Usage:
#   ./setup/connect-workshop.sh user-NN '<password>'
#
# Where user-NN and the password come from the slip your workshop operator
# handed you. Two args, that's it — every other setting (which cluster,
# which Cassandra/WxD hostname, which ports) is baked into this bundle at
# build time.
#
# What this script does:
#   1. Reads cluster endpoints from setup/workshop.env (shipped in the bundle).
#   2. Writes a .env file in the repo root with your slip credentials + the
#      cluster endpoints. Your exercise app will load .env at runtime.
#   3. Creates a .venv with cassandra-driver if you don't already have one.
#   4. Runs a connectivity smoke test:
#        - Cassandra: TLS handshake + SELECT against your per-user keyspace.
#        - watsonx.data Presto: mint Bearer token + SHOW SCHEMAS.
#      Both have to succeed before you start the exercises.
#
# If the smoke test fails, the error message tells you which surface broke
# (Cassandra vs Presto) — that's usually enough to debug, but `docs/getting-
# unstuck.md` covers the common cases.
###############################################################################

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Color helpers — no dep on lib/common.sh (attendee bundle doesn't ship it).
if [[ -t 1 ]]; then
    GREEN=$'\033[0;32m'; RED=$'\033[0;31m'; YELLOW=$'\033[0;33m'
    CYAN=$'\033[0;36m';  NC=$'\033[0m'
else
    GREEN="";  RED="";  YELLOW="";  CYAN="";  NC=""
fi
ok()   { /bin/echo "${GREEN}[OK]${NC}   $*"; }
warn() { /bin/echo "${YELLOW}[WARN]${NC} $*"; }
info() { /bin/echo "${CYAN}[INFO]${NC} $*"; }
fail() { /bin/echo "${RED}[FAIL]${NC} $*" >&2; }

usage() {
    /usr/bin/sed -n '3,25p' "$0" | /usr/bin/sed 's/^# \{0,1\}//'
}

# -- Args -------------------------------------------------------------------
if [[ $# -lt 2 ]]; then
    usage; exit 2
fi
USERNAME="$1"
PASSWORD="$2"

if ! [[ "$USERNAME" =~ ^user-[0-9]{2}$ ]]; then
    fail "Username must look like 'user-01', 'user-07', etc. Got: $USERNAME"
    exit 2
fi
# user-07 → "user07" (matches provision-schemas.sh suffix convention).
SUFFIX="${USERNAME/-/}"

# -- Cluster endpoints baked into bundle ------------------------------------
WORKSHOP_ENV="$SCRIPT_DIR/workshop.env"
if [[ ! -f "$WORKSHOP_ENV" ]]; then
    fail "setup/workshop.env not found."
    /bin/echo "  This bundle was built without cluster endpoints. Ask your"
    /bin/echo "  workshop operator to re-build the bundle against an active"
    /bin/echo "  cluster (./setup/release/build-attendee-bundle.sh)."
    exit 1
fi
# shellcheck disable=SC1090
set -a; source "$WORKSHOP_ENV"; set +a

for var in WXD_HOST PRESTO_HOST PRESTO_PORT CASSANDRA_HOST CASSANDRA_PORT; do
    if [[ -z "${!var:-}" ]]; then
        fail "$var is not set in setup/workshop.env. Re-build the bundle."
        exit 1
    fi
done

# -- Write .env -------------------------------------------------------------
ENV_FILE="$REPO_ROOT/.env"
if [[ -f "$ENV_FILE" ]]; then
    /bin/cp "$ENV_FILE" "$ENV_FILE.bak"
    info ".env existed — backed up to .env.bak"
fi

/bin/cat >"$ENV_FILE" <<EOF
# Generated by connect-workshop.sh on $(/bin/date -u '+%Y-%m-%dT%H:%M:%SZ')
# Your exercise app should load this file (python-dotenv, dotenv, etc).

# watsonx.data — Presto + Software Hub UI
WXD_HOST=${WXD_HOST}
PRESTO_HOST=${PRESTO_HOST}
PRESTO_PORT=${PRESTO_PORT}

# Cassandra (TLS-passthrough Route, NOT native CQL port 9042)
CASSANDRA_HOST=${CASSANDRA_HOST}
CASSANDRA_PORT=${CASSANDRA_PORT}
CASSANDRA_USE_SSL=true

# Per-attendee credentials from your slip
WORKSHOP_USER=${USERNAME}
WORKSHOP_PASSWORD=${PASSWORD}
WORKSHOP_SCHEMA_SUFFIX=${SUFFIX}
EOF
ok "Wrote .env at $ENV_FILE"

# -- Python venv with cassandra-driver --------------------------------------
VENV="$REPO_ROOT/.venv"
if [[ ! -x "$VENV/bin/python3" ]]; then
    info "Creating .venv (one-time, ~20s)…"
    if ! /usr/bin/python3 -m venv "$VENV" 2>/dev/null; then
        fail "Could not create .venv. Is python3 (3.10+) on PATH?"
        exit 1
    fi
fi
PY="$VENV/bin/python3"

if ! "$PY" -c "import cassandra, urllib.request" 2>/dev/null; then
    info "Installing cassandra-driver into .venv (one-time)…"
    if ! "$VENV/bin/pip" install -q --disable-pip-version-check cassandra-driver; then
        fail "pip install failed. Check your network."
        exit 1
    fi
fi
ok "Python venv ready at $VENV"

# -- Smoke test -------------------------------------------------------------
info "Running connectivity smoke test…"
if WORKSHOP_PASSWORD="$PASSWORD" "$PY" "$SCRIPT_DIR/lib/smoke_test.py"; then
    /bin/echo
    ok "All checks passed. You're ready for the first exercise prompt."
    /bin/echo
    /bin/echo "  Software Hub UI: https://${WXD_HOST}/"
    /bin/echo "  Login: ${USERNAME} / <your slip password>"
else
    rc=$?
    /bin/echo
    fail "Smoke test failed. See output above."
    /bin/echo "  If your operator just provisioned you, wait 60s and re-run."
    /bin/echo "  Otherwise: docs/getting-unstuck.md or ask the operator."
    exit "$rc"
fi
